package lab5.app

enum class StringResourceKeys {
    choose,
    chooseWaysOfSolution,
    chooseWayOneTwoThree,
    chooseObjectiveFunction,
    objectiveFunctions,
    suppliers,
    consumers,
    inputNameOfSuppliers,
    inputNameOfConsumers,
    inputAvailabilityOfSuppliers,
    inputExpectetionOfConsumers,
    inputCostOfDelivery,
    cell,
    titleMusntBeNull,
    numberMustBeInRange,
    inputError,
    showHistoryOrExit,
    inputData,
    table,
    result,
    cycleStart,
    cyclePath,
    searchOptimalSolution,
    optimalSolutionFound,
    planAlreadyOptimal,
    historyOfSolution,
    lineSeparator,
    potentialMatrix,
    leastCostMethod,
    modiMethod,
}